use crate::provider::Track;

pub enum Action {
    Quit,
    Redraw,
    ToggleLyrics,
    LyricsFinished {
        id: u64,
        result: Result<crate::provider::Lyrics, String>,
    },
    Enqueue,
    RemoveQueued,
    Back,
    ToggleHelp,
    FocusSearch,
    Insert(char),
    Backspace,
    ClearQuery,
    SubmitSearch,
    MoveDown,
    MoveUp,
    First,
    Last,
    OpenTrack,
    Discover,
    ShowPlayer,
    ShowQueue,
    ShufflePlay,
    ToggleFavorite,
    FavoriteFinished(Result<bool, String>),
    Login,
    ToggleSearchKind,
    CycleProvider,
    PlayAll,
    NextTrack,
    BrowseFinished {
        id: u64,
        result: Result<crate::provider::BrowseResults, String>,
    },
    TogglePause,
    VolumeUp,
    VolumeDown,
    ToggleMute,
    SeekRelative(i64),
    StopPlayback,
    PlaybackUpdate {
        id: u64,
        state: super::state::PlaybackState,
        elapsed_ms: u64,
        buffering: bool,
    },
    SearchFinished {
        id: u64,
        result: Result<Vec<Track>, String>,
    },
}
